version: "3.7"
services:
  backend:
    build:
      args:
        user: assessment
        uid: 1000
      context: ./
      dockerfile: ./docker/Dockerfile
    image: assessment
    env_file:
      - ./docker/backend.env
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    networks:
      - assessment
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: assessment
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: assessment_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./_data/database/:/var/lib/mysql/
    networks:
      - assessment
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8890:80
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - assessment
    depends_on:
      - backend
volumes:
  exclude:
networks:
  assessment:
    driver: bridge